// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/harungurubudi/mtsg/internal/presentation/http"
	"github.com/harungurubudi/mtsg/internal/usecase"
)

// Injectors from wire.go:

//go:generate wire
func InitializeAuthUseCase() usecase.Authentication {
	userRepository := ProvideUserRepository()
	client := ProvideRedisClient()
	adapterRepository := ProvideRedisAdapter(client)
	generatorRepository := ProvideTokenGenerator(adapterRepository)
	authentication := ProvideAuthUseCase(userRepository, generatorRepository)
	return authentication
}

//go:generate wire
func InitializeServer() *http.Server {
	handlers := ProvideHandlers()
	config := ProvideServerConfig()
	server := ProvideHTTPServer(handlers, config)
	return server
}

// wire.go:

// HandlerSet groups all handler-related providers
var HandlerSet = wire.NewSet(

	ProvideRedisClient,
	ProvideRedisAdapter,

	ProvideUserRepository,
	ProvideTokenGenerator,

	ProvideAuthUseCase,

	ProvideHandlers,
)

// ServerSet groups all server-related providers
var ServerSet = wire.NewSet(
	HandlerSet,
	ProvideServerConfig,
	ProvideHTTPServer,
)
