// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/harungurubudi/mtsg/internal/di/provider"
	"github.com/harungurubudi/mtsg/internal/presentation/http"
	"github.com/harungurubudi/mtsg/internal/usecase"
)

// Injectors from wire.go:

//go:generate wire
func InitializeAuthUseCase() usecase.Authentication {
	userRepository := provider.ProvideUserRepository()
	config := provider.ProvideConfig()
	client := provider.ProvideRedisClient(config)
	adapterRepository := provider.ProvideRedisAdapter(client)
	generatorRepository := provider.ProvideTokenGenerator(adapterRepository)
	authentication := provider.ProvideAuthUseCase(userRepository, generatorRepository)
	return authentication
}

//go:generate wire
func InitializeServer() *http.Server {
	userRepository := provider.ProvideUserRepository()
	config := provider.ProvideConfig()
	client := provider.ProvideRedisClient(config)
	adapterRepository := provider.ProvideRedisAdapter(client)
	generatorRepository := provider.ProvideTokenGenerator(adapterRepository)
	authentication := provider.ProvideAuthUseCase(userRepository, generatorRepository)
	handlers := provider.ProvideHandlers(authentication)
	factory := provider.ProvideMiddlewareFactory(authentication)
	server := provider.ProvideHTTPServer(handlers, config, factory)
	return server
}

// wire.go:

// ConfigSet groups all configuration-related providers
var ConfigSet = wire.NewSet(provider.ProvideConfig)

// HandlerSet groups all handler-related providers
var HandlerSet = wire.NewSet(
	ConfigSet, provider.ProvideRedisClient, provider.ProvideRedisAdapter, provider.ProvideUserRepository, provider.ProvideTokenGenerator, provider.ProvideAuthUseCase, provider.ProvideHandlers,
)

// MiddlewareSet groups all middleware-related providers
var MiddlewareSet = wire.NewSet(provider.ProvideMiddlewareFactory)

// ServerSet groups all server-related providers
var ServerSet = wire.NewSet(
	HandlerSet,
	MiddlewareSet, provider.ProvideHTTPServer,
)
