// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdapterRepository creates a new instance of MockAdapterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapterRepository {
	mock := &MockAdapterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapterRepository is an autogenerated mock type for the AdapterRepository type
type MockAdapterRepository struct {
	mock.Mock
}

type MockAdapterRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapterRepository) EXPECT() *MockAdapterRepository_Expecter {
	return &MockAdapterRepository_Expecter{mock: &_m.Mock}
}

// DeleteByKeys provides a mock function for the type MockAdapterRepository
func (_mock *MockAdapterRepository) DeleteByKeys(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteByKeys")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapterRepository_DeleteByKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByKeys'
type MockAdapterRepository_DeleteByKeys_Call struct {
	*mock.Call
}

// DeleteByKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockAdapterRepository_Expecter) DeleteByKeys(ctx interface{}, keys ...interface{}) *MockAdapterRepository_DeleteByKeys_Call {
	return &MockAdapterRepository_DeleteByKeys_Call{Call: _e.mock.On("DeleteByKeys",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockAdapterRepository_DeleteByKeys_Call) Run(run func(ctx context.Context, keys ...string)) *MockAdapterRepository_DeleteByKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAdapterRepository_DeleteByKeys_Call) Return(err error) *MockAdapterRepository_DeleteByKeys_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapterRepository_DeleteByKeys_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockAdapterRepository_DeleteByKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function for the type MockAdapterRepository
func (_mock *MockAdapterRepository) GetByKey(ctx context.Context, key string, receiver any) error {
	ret := _mock.Called(ctx, key, receiver)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, key, receiver)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapterRepository_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockAdapterRepository_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - receiver any
func (_e *MockAdapterRepository_Expecter) GetByKey(ctx interface{}, key interface{}, receiver interface{}) *MockAdapterRepository_GetByKey_Call {
	return &MockAdapterRepository_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, key, receiver)}
}

func (_c *MockAdapterRepository_GetByKey_Call) Run(run func(ctx context.Context, key string, receiver any)) *MockAdapterRepository_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapterRepository_GetByKey_Call) Return(err error) *MockAdapterRepository_GetByKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapterRepository_GetByKey_Call) RunAndReturn(run func(ctx context.Context, key string, receiver any) error) *MockAdapterRepository_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// IsExist provides a mock function for the type MockAdapterRepository
func (_mock *MockAdapterRepository) IsExist(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for IsExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapterRepository_IsExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExist'
type MockAdapterRepository_IsExist_Call struct {
	*mock.Call
}

// IsExist is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAdapterRepository_Expecter) IsExist(ctx interface{}, key interface{}) *MockAdapterRepository_IsExist_Call {
	return &MockAdapterRepository_IsExist_Call{Call: _e.mock.On("IsExist", ctx, key)}
}

func (_c *MockAdapterRepository_IsExist_Call) Run(run func(ctx context.Context, key string)) *MockAdapterRepository_IsExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapterRepository_IsExist_Call) Return(b bool, err error) *MockAdapterRepository_IsExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAdapterRepository_IsExist_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockAdapterRepository_IsExist_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockAdapterRepository
func (_mock *MockAdapterRepository) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapterRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockAdapterRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *MockAdapterRepository_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockAdapterRepository_Set_Call {
	return &MockAdapterRepository_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockAdapterRepository_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *MockAdapterRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdapterRepository_Set_Call) Return(err error) *MockAdapterRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapterRepository_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) error) *MockAdapterRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}
