// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/authentication.go

// Package testmock is a generated GoMock package.
package testmock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	authentication "github.com/harungurubudi/mtsg/internal/domain/authentication"
	user "github.com/harungurubudi/mtsg/internal/domain/user"
	token "github.com/harungurubudi/mtsg/pkg/token"
)

// MockAuthentication is a mock of Authentication interface.
type MockAuthentication struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationMockRecorder
}

// MockAuthenticationMockRecorder is the mock recorder for MockAuthentication.
type MockAuthenticationMockRecorder struct {
	mock *MockAuthentication
}

// NewMockAuthentication creates a new mock instance.
func NewMockAuthentication(ctrl *gomock.Controller) *MockAuthentication {
	mock := &MockAuthentication{ctrl: ctrl}
	mock.recorder = &MockAuthenticationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthentication) EXPECT() *MockAuthenticationMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthentication) Login(ctx context.Context, credential *authentication.Credential) (*authentication.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, credential)
	ret0, _ := ret[0].(*authentication.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthenticationMockRecorder) Login(ctx, credential interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthentication)(nil).Login), ctx, credential)
}

// Logout mocks base method.
func (m *MockAuthentication) Logout(ctx context.Context, accessToken token.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, accessToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthenticationMockRecorder) Logout(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthentication)(nil).Logout), ctx, accessToken)
}

// RefreshToken mocks base method.
func (m *MockAuthentication) RefreshToken(ctx context.Context, refreshToken token.Token) (*authentication.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*authentication.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthenticationMockRecorder) RefreshToken(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthentication)(nil).RefreshToken), ctx, refreshToken)
}

// VerifyToken mocks base method.
func (m *MockAuthentication) VerifyToken(ctx context.Context, token token.Token, subject string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, token, subject)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockAuthenticationMockRecorder) VerifyToken(ctx, token, subject interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockAuthentication)(nil).VerifyToken), ctx, token, subject)
}
