// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"

	"github.com/harungurubudi/mtsg/internal/domain/authentication"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthentication creates a new instance of MockAuthentication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthentication(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthentication {
	mock := &MockAuthentication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthentication is an autogenerated mock type for the Authentication type
type MockAuthentication struct {
	mock.Mock
}

type MockAuthentication_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthentication) EXPECT() *MockAuthentication_Expecter {
	return &MockAuthentication_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) Login(ctx context.Context, credential *authentication.Credential) (*authentication.Session, error) {
	ret := _mock.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authentication.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authentication.Credential) (*authentication.Session, error)); ok {
		return returnFunc(ctx, credential)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authentication.Credential) *authentication.Session); ok {
		r0 = returnFunc(ctx, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authentication.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authentication.Credential) error); ok {
		r1 = returnFunc(ctx, credential)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthentication_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthentication_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *authentication.Credential
func (_e *MockAuthentication_Expecter) Login(ctx interface{}, credential interface{}) *MockAuthentication_Login_Call {
	return &MockAuthentication_Login_Call{Call: _e.mock.On("Login", ctx, credential)}
}

func (_c *MockAuthentication_Login_Call) Run(run func(ctx context.Context, credential *authentication.Credential)) *MockAuthentication_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authentication.Credential
		if args[1] != nil {
			arg1 = args[1].(*authentication.Credential)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthentication_Login_Call) Return(session *authentication.Session, err error) *MockAuthentication_Login_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockAuthentication_Login_Call) RunAndReturn(run func(ctx context.Context, credential *authentication.Credential) (*authentication.Session, error)) *MockAuthentication_Login_Call {
	_c.Call.Return(run)
	return _c
}
