// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"

	"github.com/harungurubudi/mtsg/pkg/token"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGeneratorRepository creates a new instance of MockGeneratorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeneratorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeneratorRepository {
	mock := &MockGeneratorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGeneratorRepository is an autogenerated mock type for the GeneratorRepository type
type MockGeneratorRepository struct {
	mock.Mock
}

type MockGeneratorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeneratorRepository) EXPECT() *MockGeneratorRepository_Expecter {
	return &MockGeneratorRepository_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockGeneratorRepository
func (_mock *MockGeneratorRepository) Generate(ctx context.Context, claims token.Claims) (token.Token, error) {
	ret := _mock.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 token.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, token.Claims) (token.Token, error)); ok {
		return returnFunc(ctx, claims)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, token.Claims) token.Token); ok {
		r0 = returnFunc(ctx, claims)
	} else {
		r0 = ret.Get(0).(token.Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, token.Claims) error); ok {
		r1 = returnFunc(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGeneratorRepository_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockGeneratorRepository_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - claims token.Claims
func (_e *MockGeneratorRepository_Expecter) Generate(ctx interface{}, claims interface{}) *MockGeneratorRepository_Generate_Call {
	return &MockGeneratorRepository_Generate_Call{Call: _e.mock.On("Generate", ctx, claims)}
}

func (_c *MockGeneratorRepository_Generate_Call) Run(run func(ctx context.Context, claims token.Claims)) *MockGeneratorRepository_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 token.Claims
		if args[1] != nil {
			arg1 = args[1].(token.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGeneratorRepository_Generate_Call) Return(token1 token.Token, err error) *MockGeneratorRepository_Generate_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *MockGeneratorRepository_Generate_Call) RunAndReturn(run func(ctx context.Context, claims token.Claims) (token.Token, error)) *MockGeneratorRepository_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockGeneratorRepository
func (_mock *MockGeneratorRepository) Revoke(ctx context.Context, token1 token.Token) error {
	ret := _mock.Called(ctx, token1)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, token.Token) error); ok {
		r0 = returnFunc(ctx, token1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGeneratorRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockGeneratorRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - token1 token.Token
func (_e *MockGeneratorRepository_Expecter) Revoke(ctx interface{}, token1 interface{}) *MockGeneratorRepository_Revoke_Call {
	return &MockGeneratorRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, token1)}
}

func (_c *MockGeneratorRepository_Revoke_Call) Run(run func(ctx context.Context, token1 token.Token)) *MockGeneratorRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 token.Token
		if args[1] != nil {
			arg1 = args[1].(token.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGeneratorRepository_Revoke_Call) Return(err error) *MockGeneratorRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGeneratorRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, token1 token.Token) error) *MockGeneratorRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockGeneratorRepository
func (_mock *MockGeneratorRepository) Validate(ctx context.Context, token1 token.Token) (*token.Claims, error) {
	ret := _mock.Called(ctx, token1)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *token.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, token.Token) (*token.Claims, error)); ok {
		return returnFunc(ctx, token1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, token.Token) *token.Claims); ok {
		r0 = returnFunc(ctx, token1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, token.Token) error); ok {
		r1 = returnFunc(ctx, token1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGeneratorRepository_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockGeneratorRepository_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token1 token.Token
func (_e *MockGeneratorRepository_Expecter) Validate(ctx interface{}, token1 interface{}) *MockGeneratorRepository_Validate_Call {
	return &MockGeneratorRepository_Validate_Call{Call: _e.mock.On("Validate", ctx, token1)}
}

func (_c *MockGeneratorRepository_Validate_Call) Run(run func(ctx context.Context, token1 token.Token)) *MockGeneratorRepository_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 token.Token
		if args[1] != nil {
			arg1 = args[1].(token.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGeneratorRepository_Validate_Call) Return(claims *token.Claims, err error) *MockGeneratorRepository_Validate_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockGeneratorRepository_Validate_Call) RunAndReturn(run func(ctx context.Context, token1 token.Token) (*token.Claims, error)) *MockGeneratorRepository_Validate_Call {
	_c.Call.Return(run)
	return _c
}
