// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"

	"github.com/harungurubudi/mtsg/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetOneByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetOneByEmail(ctx context.Context, email user.Email) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetOneByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Email) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.Email) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.Email) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetOneByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOneByEmail'
type MockUserRepository_GetOneByEmail_Call struct {
	*mock.Call
}

// GetOneByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email user.Email
func (_e *MockUserRepository_Expecter) GetOneByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetOneByEmail_Call {
	return &MockUserRepository_GetOneByEmail_Call{Call: _e.mock.On("GetOneByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetOneByEmail_Call) Run(run func(ctx context.Context, email user.Email)) *MockUserRepository_GetOneByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.Email
		if args[1] != nil {
			arg1 = args[1].(user.Email)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetOneByEmail_Call) Return(user1 *user.User, err error) *MockUserRepository_GetOneByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_GetOneByEmail_Call) RunAndReturn(run func(ctx context.Context, email user.Email) (*user.User, error)) *MockUserRepository_GetOneByEmail_Call {
	_c.Call.Return(run)
	return _c
}
